### ISSUE TITLE
Release on xELPA

### ISSUE THREAD

**Issue by NobbZ** [ayrat555/mix.el#1]
> Currently, mix.el is not available through MELPA. If there is a demand for it, I'll upload the package there.

Please do, as installing from xELPA is a lot easier than from source when doing declarative package management on nixOS.

**Comment by ayrat555** [comment]
I'll submit this package to MELPA in 10 hours in the morning in my timezone

**Comment by ayrat555** [comment]
https://github.com/melpa/melpa/pull/6800

**Comment by ayrat555** [comment]
@NobbZ https://melpa.org/#/mix
