### ISSUE TITLE
Make opening errors in compilation work in umbrella apps

### ISSUE THREAD

**Issue by smoes** [ayrat555/mix.el#11]
First off: Great work, thanks!

I'd just wanted to ask what is needed to make errors openable in an umbrella app.
Since the compiler compiles apps recursively, the relative file paths in the output don't match in the root path of the umbrella application. The errors can be opened in compilation mode, but not found, due to the these paths. Any idea how to change that?

**Comment by ayrat555** [comment]
@smoes hello. thanks for opening the issue

 please let me know if https://github.com/ayrat555/mix.el/pull/12 works

**Comment by smoes** [comment]
@ayrat555 works like a charm. Thanks a lot, this will save me so much time! Let me know if I could [buy you a coffee](https://www.buymeacoffee.com/) or similar...

**Comment by ayrat555** [comment]
@smoes I have paypal. 

https://www.paypal.com/paypalme/AyratBadykov

thank you!
