### ISSUE TITLE
Alchemist resurrection

### ISSUE THREAD

**Issue by Sasanidas** [ayrat555/mix.el#7]
Hello @ayrat555 ,

I've been involve the thread of the alchemist resurrection https://github.com/tonini/alchemist.el/issues/371 , which I decided that I would fork the project and cut down some things.

Your package is a great way to interact with mix, the problem is that it clashes with the mix functionality of alchemist(now https://github.com/Sasanidas/Apprentice), so I'm starting to add your changes back to apprentice https://github.com/Sasanidas/Apprentice/commit/e7166f0f022346dea4b7bdc50d8aa08f5a52db80.

I hope that's good for you, and again, thanks for this amazing package.

Regards

**Comment by ayrat555** [comment]
@Sasanidas I think we can find a workaround? maybe I can fix all clashes / conflicts in this package so you can use it as an external package?

**Comment by Sasanidas** [comment]
The main thing is that mix.el implements some functions that are not strictly related to mix (mostly because you need, for example to take the project root in order to launch the mix command).

But in Apprentice, these functionalities are in different places, we can ignore these duplication, and if I install mix with apprentice they can work separately, but I don't think it's ideal.

I can propose a couple of solutions:

- Remove the entire mix functionality of Apprentice and rely only on mix.el
- Take the functionality of mix.el into Apprentice (this was my original idea)
- Keep both, so both "do the same"

I do have mix feeling about it (pun intended), for one hand, I totally understand that some people want a mix package to do one thing and do it well without all the code in Apprentice, but in the other hand, I'm a fan of cohesion and code that's in the same repository can be couple in a better way.

I think both can co-exist, I'm not a big fan of removing the mix functionality from Apprentice.

Let me know what do you think :wave:

**Comment by ayrat555** [comment]
@Sasanidas feel free to use the code of this project. it's open source under MIT, anyone can use and modify it

Just one request, would be nice to add me as the co-author of this commit

**Comment by Sasanidas** [comment]
> @Sasanidas feel free to use the code of this project. it's open source under MIT, anyone can use and modify it
> 
> Just one request, would be nice to add me as the co-author of this commit

Sure, I'll attribute the contribution, thanks for the understanding :+1: 

Regards.
